FROM php:8.4-fpm-alpine

WORKDIR /app

# Installation des dépendances système + Bun
RUN apk update && apk upgrade && \
    apk add --no-cache \
        bash \
        curl \
        nginx \
        supervisor \
        mysql-client \
        git \
        unzip \
        redis \
        libzip-dev \
        oniguruma-dev \
        autoconf \
        g++ \
        make \
        linux-headers \
        libtool \
        shadow \
        zip \
    && curl -fsSL https://bun.sh/install | bash \
    && docker-php-ext-configure zip \
    && docker-php-ext-install -j$(nproc) \
        pdo \
        pdo_mysql \
        bcmath \
        opcache \
        zip \
    && pecl install redis xdebug \
    && docker-php-ext-enable redis xdebug

# Nettoyage du cache
RUN rm -rf /var/cache/apk/*

# Ajouter Bun au PATH
ENV PATH="/root/.bun/bin:${PATH}"

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY ./appli /app

RUN chown -R www-data:www-data /app/storage /app/bootstrap/cache \
    && chmod -R 775 /app/storage /app/bootstrap/cache

COPY ./docker/dev/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/dev/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 9000 80 5173

ENV APP_ENV=local
ENV APP_DEBUG=true

COPY ./docker/dev/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
