services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.dev
    restart: unless-stopped
    environment:
      - AUTORUN_ENABLED=true
    ports:
      - 8000:80
    volumes:
      - ./appli:/app
    depends_on:
      - redis
      - db

  bun:
    image: oven/bun:latest
    working_dir: /app
    command: sh -c "bun install && bun run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./appli:/app
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - app

  # Redis Service
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data

  # MySQL Service
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: exam224
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 100M
    depends_on:
      - db

# Volumes
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
